Feature/siv5 scaling
march-works/simple-image-viewer pull request #52
Opened 2023-04-22 20:11 UTC by m-taira701

### 変更の概要
拡大縮小機能の実装

### やったこと
以下の機能の実装
1. ボタン押下による画像の拡大縮小
2. マウスホイールによる画像の拡大縮小
3. マウスを使って画像位置の調整
4. キーボードから拡大縮小を行う

### 課題
以下、特に不安な点です。
- CSSの書き方
- 使用感のイメージのズレ

2023-04-24 16:31 UTC, march101348 requested changes

2023-04-24 16:31 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +  handleMouseUp: (e: MouseEvent) => void;
コールバックにわたす情報は最小限が望ましいです。
親コンポーネントとして必要なのはposition x, yの情報だけなはずなのでそれ以外の必要な処理は子コンポーネントでお願いします。

2023-04-24 16:31 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +            class="w-20 h-20 flex cursor-pointer opacity-50 transition-colors hover:bg-neutral-800 hover:opacity-100 items-center justify-center"
位置と見え方はこれでOKです。
ホバー時にアイコンの背景が不透明になるのが割と違和感あるので背景は透明のままでいい気がします。

2023-04-24 16:31 UTC, march101348 commented on src/pages/viewer/ViewerTab.tsx
> +  const handleMouseDown = (e: MouseEvent) => {
あらゆるマウスボタンに反応するようになっているので左クリックのみにイベントを絞ってほしいです。

2023-04-24 16:31 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +              transform: `scale(${props.imageScale}) translate(${props.position.x}px, ${props.position.y}px)`,
画像の倍率の初期値が画像の解像度依存になっているのですが、個人的には元の親コンポーネントにフィットさせる挙動のほうが好みなので修正お願いします。
また、画像を移動した際に１つ前の画像の倍率・移動情報が残っていますが、リセットする挙動の方が好みなのでこちらも修正お願いします。

2023-05-03 20:38 UTC, m-taira701 commented on src/features/image/routes/ImageCanvas.tsx
> +  handleMouseUp: (e: MouseEvent) => void;
コールバックで渡す情報を最小限にするために拡大・縮小・移動といった出力された画像そのものに対する更新は子コンポーネント内部で行ったほうが良いと解釈しました。
その場合、position x, yも親コンポーネントに渡さずに子コンポーネントで完結できそうだと感じたのですがいかがでしょうか？認識できていない仕様などありましたら教えていただきたいです。

2023-05-07 07:29 UTC, m-taira701 commented
以下の通り、指摘事項を修正しました。

### 指摘内容
1. 親コンポーネントとして必要なのはposition x, yの情報だけなはずなのでそれ以外の必要な処理は子コンポーネントで行う。
2. ホバー時に拡大・縮小アイコンの背景が不透明になるのには違和感があるため透明のままにする。
3. 画像の移動にはあらゆるマウスボタンに反応するようになっているので左クリックのみにイベントを絞る。
4. 画像の倍率の初期値が画像の解像度依存になっているが、親コンポーネントにフィットさせる挙動に戻す。
5. 画像を移動した際に１つ前の画像の倍率・移動情報が残っているが、リセットさせる。

### 懸念点
1について、handleMouse**を子コンポーネントに移行しましたが、子コンポーネントと親コンポーネントのそれぞれで位置を調整するために、setPositionを追加しました。実装イメージと相違あれば教えていただきたいです。
5について、SetViewingのタイミングで倍率・移動情報を初期化させるresetStatusを使用しています。現状の場合、画像を切替えた時に元の画像の状態で倍率・位置情報がリセットされてそれから新しい画像に変更するような挙動になっています。もしより良い実装方法があれば教えていただきたいです。

2023-05-07 11:15 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +  handleMouseUp: (e: MouseEvent) => void;
考え方はそれでOKです。多分この辺は開発者の好みなので普遍的な感性ではないことはご注意ください。
同様にwheelEventもImageCanvas側でzoomIn, zoomOutに振り分ける実装にしたほうが個人的には好みです。

2023-05-07 11:34 UTC, march101348 requested changes

2023-05-07 11:34 UTC, march101348 commented on src/pages/viewer/ViewerTab.tsx
> +    resetStatus();
createEffectで画像変更時にresetかけたほうがきれいだと思います。

2023-05-07 11:34 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +        <div class="absolute fixed bottom-0 left-0 w-full flex justify-center items-end">
absoluteとfixedが両方指定される必要はないはずです。
VSCodeの推奨拡張をmasterにコミットしたので、一旦取り込んだ上で警告出ている箇所を修正お願いします。

2023-05-07 11:34 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +            class="w-20 h-20 flex cursor-pointer opacity-50 transition-colors hover:opacity-100 items-center justify-center"
透過50%だと案外目立つので30%でおねがいします。

2023-05-07 11:34 UTC, march101348 commented on src/features/image/routes/ImageCanvas.tsx
> +  const handleMouseMove = (event: MouseEvent) => {
画像の移動範囲は画面からはみ出さないほうが好みです。
難しければやらなくても大丈夫です。

2023-05-28 04:40 UTC, march101348 approved these changes

2023-05-28 04:40 UTC, merged